apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rabbit-producer.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{ toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{ toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
              - name: RABBITMQ_USERNAME
                value: {{ .Values.rabbitmq.username }}
              - name: RABBITMQ_PASSWORD
                value: {{ .Values.rabbitmq.password }}
              command: ["python", "producer.py"]
              args: ["-p", "{{ .Values.rabbitmq.port }}", "-s", "{{ .Values.rabbitmq.server }}", "-m", "{{ .Values.message}}"]
              resources:
                {{ toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{ toYaml . | nindent 12 }}
          {{- end }}
