name: Build and release containers

on:
  workflow_run:
    workflows: ["Pylint and Pytest"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

  docker:
    needs: on-success
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push consumer
        uses: docker/build-push-action@v5
        with:
          context: ./consumer
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ofirdassa/k8s_rabbit:consumer
      -
        name: Build and push producer
        uses: docker/build-push-action@v5
        with:
          context: ./producer
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ofirdassa/k8s_rabbit:producer