name: 'CD'   

on:
  push:
    branches:
      - master

jobs:
  check_workflow:
    strategy:
      matrix:
        include:
          - workflow: CI-charts
          - workflow: CI-containers
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: Check Workflows
        id: check_workflows
        uses: ./.github/actions/check-workflows
        with:
          workflow: ${{ matrix.workflow }}

      - name: Run if both workflows succeeded
        shell: bash
        run: echo "Both workflows succeeded!"
        if: ${{ needs.check_workflows.outputs.result == 'success' }}

  deployment:
    needs: check_workflow
    runs-on: self-hosted
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'

    - name: 'Setup helm'
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      id: install

    - name: 'Helm upgrade'
      run: |
        helm upgrade -i consumer charts/consumer --set rabbitmq.password="${{ secrets.RABBITMQ_PASSWORD }}" -n rabbitmq --create-namespace
        helm upgrade -i producer charts/producer --set rabbitmq.password="${{ secrets.RABBITMQ_PASSWORD }}" --set message="This is a test from Ofir to rabbitmq ns" -n rabbitmq