name: 'CD'   

on:
  workflow_run:
    workflows: ["test-charts"]
    types:
      - completed

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'

    - name: 'Setup helm'
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      id: install

    - name: 'Helm upgrade'
      run: |
        helm upgrade -i consumer charts/consumer --set rabbitmq.password="${{ secrets.RABBITMQ_PASSWORD }}" -n rabbitmq --create-namespace
        helm upgrade -i producer charts/producer --set rabbitmq.password="${{ secrets.RABBITMQ_PASSWORD }}" --set message="This is a test from Ofir to rabbitmq ns" -n rabbitmq