name: 'Deploy helm charts'   

on:
  workflow_run:
    workflows: ["Release Charts"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      
  deployment:
    needs: on-success
    runs-on: self-hosted
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'

    - name: 'Setup helm'
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      id: install

    - name: 'Helm repo add & update'
      run: |
        helm repo add k8s-project https://k8s-project.parligator.com
        helm repo update

    - name: 'Helm upgrade'
      run: |
        helm upgrade -i consumer k8s-project/rabbit-consumer --set rabbitmq.password="${{ secrets.RABBITMQ_PASSWORD }}" -n rabbitmq --create-namespace
        helm upgrade -i producer k8s-project/rabbit-producer --set rabbitmq.password="${{ secrets.RABBITMQ_PASSWORD }}" --set message="This is a test from Ofir to rabbitmq ns" -n rabbitmq