name: Pylint and Black formatting

on:
  pull_request:
    branches:
      - master

jobs:
  pylint-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          cd consumer && pip install -r requirements.txt
          cd ../producer && pip install -r requirements.txt

      - uses: microsoft/action-python@0.7.0
        name: consumer
        with:
          workdir: 'consumer'
          black: true
          pylint: true
          toml: 'consumer/pyproject.toml'

      - uses: microsoft/action-python@0.7.0
        name: producer
        with:
          workdir: 'producer'
          black: true
          pylint: true
          toml: 'producer/pyproject.toml'