name: Pylint and Pytest

on:
  pull_request:
    branches:
      - master

jobs:
  pylint-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/action-python@0.7.0
        name: consumer
        with:
          workdir: './consumer'
          pylint: true
          pytest: true
        
      - uses: microsoft/action-python@0.7.0
        name: producer
        with:
          workdir: './producer'
          pylint: true
          pytest: true